[package]
name = "takemeds-bot"
version = "0.1.0"
edition="2021"

[dependencies]
teloxide = { version = "0.12.2", features = ["macros"] }
tokio = { version = "1.12.0", features = ["full"] }
sqlx = { version = "0.6.3", features = ["sqlite", "runtime-tokio-rustls"] }